name: ECR Image Signature Creation & Inspection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * 1

jobs:
  image-integrity:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: AWS_TO_GITHUB_OIDC_FEDERATED_ACCESS
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2.0.1

    - name: Verify image
      uses: anhussain90/aws-ecr-signer/.github/actions/aws-ecr-signer@main
      with:
        ecr_tagged_image: ${{ secrets.ECR_REPO_URL }}:${{ vars.IMAGE_TAG }} # {account}.dkr.ecr.{region}.amazonaws.com/{repo_name}:{image_tag}
        image_sign_inspect: 'true'
